version: '3.8'
name: foodgram


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_production:/var/lib/postgresql/data
  backend:
    image: getchdnk/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - data_production:/app/data/
      - static_production:/app/static/
      - media_production:/app/media/
  frontend:
    image: getchdnk/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_production:/frontend_static
      - media_production:/media
  gateway:
    image: getchdnk/foodgram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    volumes:
      - ./etc/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_production:/var/html/static/
      - media_production:/var/html/media/
    ports:
      - 8000:80

volumes:
  postgres_production:
  static_production:
  media_production:
  data_production: