version: '3.8'
name: foodgram


services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_production:/var/lib/postgresql/data
  backend:
    container_name: foodgram_backend
    image: getchdnk/foodgram_backend:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - data_production:/app/data/
      - static_production:/app/static/
      - media_production:/app/media/

  frontend:
    container_name: foodgram_frontend
    image: getchdnk/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  
  gateway:
    container_name: foodgram_gateway
    image: getchdnk/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - frontend
      - backend
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/app/data/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/app/data/api/docs/openapi-schema.yml
      - static_production:/app/static/
      - media_production:/app/media/
      - data_production:/app/data/
    ports:
      - "8000:80"
    restart: always

volumes:
  postgres_production:
  static_production:
  media_production:
  data_production: