version: '3.8'
name: foodgram


services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_production:/var/lib/postgresql/data
  backend:
    container_name: foodgram_backend
    image: getchdnk/foodgram_backend:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - data_production:/app/api/docs/
      - static_production:/app/static/
      - media_production:/app/media/

  frontend:
    container_name: foodgram_frontend
    image: getchdnk/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  gateway:
    container_name: foodgram_gateway
    image: nginx:1.19.3
    env_file: .env
    depends_on:
      - frontend
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_production:/var/html/static/
      - media_production:/var/html/media/
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  postgres_production:
  static_production:
  media_production:
  data_production: