version: '3.8'
name: foodgram
services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    build:
      context: ../backend/foodgram/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - data_data:/code/data/
      - static_data:/code/static/
      - media_data:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/code/data/frontend/result_build/
    depends_on:
      - backend

  gateway:
    container_name: foodgram_gateway
    build: ./infra/
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/code/data/frontend/result_build/
      - ../docs/redoc.html:/code/data/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/code/data/api/docs/openapi-schema.yml
      - static_data:/code/static/
      - media_data:/code/media/
      - data_data:/code/data/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_data:
  media_data:
  data_data: