# Generated by Django 3.2.16 on 2023-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такое название рецепта уже есть!'}, max_length=200, unique=True, verbose_name='Название рецепта'),
        ),
    ]
