# Generated by Django 3.2.3 on 2023-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230618_1244'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='Уникальное_избранное',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='Уникальный_ингредиент',
        ),
        migrations.RemoveConstraint(
            model_name='shopingcard',
            name='Уникальная_корзина',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='uniq_tags',
        ),
        migrations.RemoveConstraint(
            model_name='taginrecipe',
            name='Уникальный_тег_рецепта',
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_favourites'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='uniq_ingredient_in_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shopingcard',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_shopingcard_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'color', 'slug'), name='uniq_tag'),
        ),
        migrations.AddConstraint(
            model_name='taginrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='uniq_tag_in_recipe'),
        ),
    ]
